### ISSUE TITLE
Unable to obtain certificate for web-sites with non 443 port for HTTPS

### ISSUE THREAD

**Issue by mstyura** [johncrisostomo/get-ssl-certificate#19]
The following snippet does not work:
```
const certificate = await sslCertificate.get("https://localhost:22281")
console.log("certificate: ", certificate)
```
Producing error like this
```
2018-11-06T07:43:52.123Z [ { Error: getaddrinfo ENOTFOUND https://localhost:22281 https://localhost:22281:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'https://localhost:22281',
    host: 'https://localhost:22281',
    port: 443 } ]
```

This happens because library states that the argument is URL, but it is [passed as hostname to `options`](https://github.com/johncrisostomo/get-ssl-certificate/blob/master/index.js#L28). 
One way to fix it is to manually parse provided URL and extract host name, path, protocol and port
```
const url = require('url')

const targetUrl = url.parse(arugmentURL)

https.get({
        hostname: targetUrl.hostname,
        port: targetUrl.port,
        protocol: targetUrl.protocol,
        path: targetUrl.path,
        ... })
```

**Comment by plambhsa** [comment]
Yes, we are testing our auth server that we host locally, and could use this as well. I'm going to try and submit a PR for this.

**Comment by johncrisostomo** [comment]
Thanks both for reporting and fixing this issue. Closing this now as it is already fixed with https://github.com/johncrisostomo/get-ssl-certificate/releases/tag/v2.3.0
