### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by DanielRuf** [johncrisostomo/get-ssl-certificate#23]
It seems there are unit tests but they are not run on CI or on any PR and commit.

**Comment by johncrisostomo** [comment]
Hello, seems that the CI pipeline is acting a bit wonky. I just opened a PR and after a few commits, it was building again.

**Comment by DanielRuf** [comment]
I think it is working now bdcazse of https://github.com/johncrisostomo/get-ssl-certificate/commit/6bc6b0d6ea1feb3aa350c3c5f64e54938f062d2f

Why not both in the script section (2 lines startjng with a `-`)?

**Comment by DanielRuf** [comment]
I think it is working now because of https://github.com/johncrisostomo/get-ssl-certificate/commit/6bc6b0d6ea1feb3aa350c3c5f64e54938f062d2f

Why not both in the script section (2 lines starting with a `-`)?
