### ISSUE TITLE
Update NPM for to see typo fix in readme.md

### ISSUE THREAD

**Issue by JavaScriptDude** [johncrisostomo/get-ssl-certificate#5]
Please update NPM as it still shows the typo that is fixed with [Aug 9, 2007 commit](https://github.com/johncrisostomo/get-ssl-certificate/commit/0306390a0f6f5d923cbb1d69043f5623ae238a6c#diff-04c6e90faac2675aa89e2176d2eec7d8)

Thanks!
Tim

**Comment by johncrisostomo** [comment]
Thanks you @JavaScriptDude (Tim)! I just pushed https://github.com/johncrisostomo/get-ssl-certificate/releases/tag/v2.1.0 today and it should be updated now. Cheers!
